SELECT codigo, razao_social, telefone FROM CLIENTES
INNER JOIN UF ON CLIENTES.id_uf = UF.id
INNER JOIN CLIENTES_TELEFONES ON CLIENTE.id = CLIENTES_TELEFONES.client_id
INNER JOIN TELEFONES ON CLIENTES_TELEFONES.telefone_id = TELEFONES.id
WHERE codigo LIKE "SP";